require 'spec'
require 'topo_xbar'

local s = spec.Spec:new()
local b = s:builder()

b:component('mult', 'mult')
    b:parameter('WIDTH')
	b:clock_sink('clk', 'clk')
	b:interface('input_a', 'data', 'in', 'clk')
		b:signal('data', 'i_a', 'WIDTH')
		b:signal('valid', 'i_a_valid')
		b:signal('ready', 'o_a_ready')
	b:interface('input_b', 'data', 'in', 'clk')
		b:signal('data', 'i_b', 'WIDTH')
		b:signal('valid', 'i_b_valid')
		b:signal('ready', 'o_b_ready')
	b:interface('output', 'data', 'out', 'clk')
		b:signal('data', 'o_result', 'WIDTH')
		b:signal('valid', 'o_result_valid')
		b:signal('ready', 'i_result_ready')

b:component('add', 'add')
    b:parameter('WIDTH')
	b:clock_sink('clk', 'clk')
	b:interface('input_a', 'data', 'in', 'clk')
		b:signal('data', 'i_a', 'WIDTH')
		b:signal('valid', 'i_a_valid')
		b:signal('ready', 'o_a_ready')
	b:interface('input_b', 'data', 'in', 'clk')
		b:signal('data', 'i_b', 'WIDTH')
		b:signal('valid', 'i_b_valid')
		b:signal('ready', 'o_b_ready')
	b:interface('output', 'data', 'out', 'clk')
		b:signal('data', 'o_result', 'WIDTH')
		b:signal('valid', 'o_result_valid')
		b:signal('ready', 'i_result_ready')

b:system('the_sys', topo_xbar)
	b:instance('the_mult', 'mult')
		b:defparam('WIDTH', 16)
	b:instance('the_add', 'add')
		b:defparam('WIDTH', 16)
	b:export('clk', 'clock', 'in')
	b:link('clk', 'the_mult.clk')
	b:link('clk', 'the_add.clk')
	b:link('the_mult.output', 'the_add.input_a')

s:submit()
